"""initial_migration_create_tables

Revision ID: a466bce3893b
Revises:
Create Date: 2025-07-02 01:21:50.585755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Add this import


# revision identifiers, used by Alembic.
revision: str = 'a466bce3893b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('interview',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_id'), 'interview', ['id'], unique=False)
    op.create_index(op.f('ix_interview_status'), 'interview', ['status'], unique=False)
    op.create_index(op.f('ix_interview_user_id'), 'interview', ['user_id'], unique=False)
    op.create_table('answerblock',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=False),
    sa.Column('json_payload', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answerblock_id'), 'answerblock', ['id'], unique=False)
    op.create_index(op.f('ix_answerblock_interview_id'), 'answerblock', ['interview_id'], unique=False)
    op.create_index(op.f('ix_answerblock_phase'), 'answerblock', ['phase'], unique=False)
    op.create_table('bpmndiagram',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('xml', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('svg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bpmndiagram_id'), 'bpmndiagram', ['id'], unique=False)
    op.create_index(op.f('ix_bpmndiagram_interview_id'), 'bpmndiagram', ['interview_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bpmndiagram_interview_id'), table_name='bpmndiagram')
    op.drop_index(op.f('ix_bpmndiagram_id'), table_name='bpmndiagram')
    op.drop_table('bpmndiagram')
    op.drop_index(op.f('ix_answerblock_phase'), table_name='answerblock')
    op.drop_index(op.f('ix_answerblock_interview_id'), table_name='answerblock')
    op.drop_index(op.f('ix_answerblock_id'), table_name='answerblock')
    op.drop_table('answerblock')
    op.drop_index(op.f('ix_interview_user_id'), table_name='interview')
    op.drop_index(op.f('ix_interview_status'), table_name='interview')
    op.drop_index(op.f('ix_interview_id'), table_name='interview')
    op.drop_table('interview')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
